updating dependencies.

diff --git a/ci.yml b/ci.yml
--- a/ci.yml
+++ b/ci.yml
@@ -2,15 +2,55 @@ name: CI
 
 on:
   pull_request:
-    branches:
-      - init
+    types: [opened, synchronize, reopened]
 
 jobs:
   pr_validator:
     runs-on: ubuntu-latest
     steps:
-    - name: PR validation
-      run: echo "Run PR Validation here."
+      - name: Validate branch name
+        uses: deepakputhraya/action-branch-name@master
+        with:
+          regex: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\/AB\#[0-9]{5}\-[a-zA-Z0-9-/]+$'
+          allowed_prefixes: 'feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert'
+          ignore: master,staging,develop, init
+          min_length: 5
+          max_length: 50
+      - uses: TimonVS/pr-labeler-action@v3
+        with:
+          configuration-path: .github/pr-labeler.yml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - uses: amannn/action-semantic-pull-request@v5
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          types: |
+            feat
+            fix
+            docs
+            style
+            refactor
+            perf
+            test
+            build
+            ci
+            chore
+            revert
+          requireScope: false
+          subjectPattern: ^AB\#[0-9]{5}.*$
+          subjectPatternError: |
+            The subject "{subject}" found in the pull request title "{title}"
+            didn't match the configured pattern. Please ensure that the subject
+            doesn't start with an uppercase character.
+          ignoreLabels: |
+            bot
+            ignore-semantic-pull-request
+          headerPattern: '^(\w*): (.*)$'
+          headerPatternCorrespondence: type, subject
+          wip: true
+          validateSingleCommit: true
+          validateSingleCommitMatchesPrTitle: true
   test_suite:
     runs-on: ubuntu-latest
     needs: pr_validator
@@ -18,6 +58,8 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        repository: ${{ github.event.pull_request.head.repo.full_name }}
+        ref: ${{ github.event.pull_request.head.ref }}
     - uses: actions/setup-python@v4
       with:
         python-version: '3.8'
@@ -37,10 +79,10 @@ jobs:
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: poetry install --no-interaction --no-root
     - name: Run test suite here
-      run: poetry run pytest --cov=tests/ --cov-report xml:coverage.xml
+      run: make test-ci
     - uses: actions/upload-artifact@v3
       with:
-        name: test_coverage_report
+        name: coverage
         path: coverage.xml
         retention-days: 5
     - name: Pytest coverage comment
@@ -54,6 +96,8 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        repository: ${{ github.event.pull_request.head.repo.full_name }}
+        ref: ${{ github.event.pull_request.head.ref }}
     - uses: actions/setup-python@v4
       with:
         python-version: '3.8'
@@ -72,8 +116,36 @@ jobs:
     - name: Install dependencies
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: poetry install --no-interaction --no-root
-    - name: Run lint checks here
-      run: echo "Run lint checks here."
+    - name: Run pylint checks here
+      run: |
+        poetry run pylint $(git ls-files '*.py') -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylint.log
+        [ -s pylint.log ] || echo 'No Pylint error found..' > pylint.log
+    - uses: actions/upload-artifact@v1
+      with:
+        name: pylintlog
+        path: pylint.log
+    - name: Comment pylint logs in PR
+      uses: machine-learning-apps/pr-comment@master
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        path: pylint.log
+    - name: Run flake8 checks here
+      run: |
+        poetry run flake8 --exit-zero --output-file=flake8.txt sample_components tests
+        [ -s flake8.txt ] || echo 'No Flake8 error found..' > flake8.txt
+    - uses: actions/upload-artifact@v1
+      with:
+        name: flake8_reports
+        path: flake8.txt
+    - name: comment Flake8 logs in PR
+      uses: machine-learning-apps/pr-comment@master
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        path: flake8.txt
+    - name: Run static typing with mypy
+      run: poetry run mypy --config-file pyproject.toml ./
   formatting_checks:
     runs-on: ubuntu-latest
     needs: pr_validator
@@ -81,6 +153,8 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        repository: ${{ github.event.pull_request.head.repo.full_name }}
+        ref: ${{ github.event.pull_request.head.ref }}
     - uses: actions/setup-python@v4
       with:
         python-version: '3.8'
@@ -99,6 +173,20 @@ jobs:
     - name: Install dependencies
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: poetry install --no-interaction --no-root
+    - name: Autoformat check and fix
+      run: |
+        poetry run isort --settings-path pyproject.toml ./
+        poetry run isort --diff --check-only --settings-path pyproject.toml ./
+        poetry run black --config pyproject.toml ./
+        poetry run black --diff --check --config pyproject.toml ./
+        poetry run darglint --verbosity 2 sample_components tests
+        poetry run pyupgrade --exit-zero-even-if-changed --py38-plus **/*.py
+    - uses: psf/black@stable
+      with:
+        options: "--check --verbose"
+        src: "./sample_components"
+        jupyter: true
+        version: "22.10"
     - name: Run formatting checks here
       run: echo "Run formatting checks here."
   security_checks:
@@ -108,6 +196,8 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        repository: ${{ github.event.pull_request.head.repo.full_name }}
+        ref: ${{ github.event.pull_request.head.ref }}
     - uses: actions/setup-python@v4
       with:
         python-version: '3.8'
@@ -126,8 +216,29 @@ jobs:
     - name: Install dependencies
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: poetry install --no-interaction --no-root
-    - name: Run security checks here
-      run: echo "Run security checks here."
+    - name: Run bandit checks here
+      run: |
+        poetry run bandit --exit-zero --format json --output bandit-report.json -r sample_components tests
+        [ -s bandit-report.json ] || echo '{"error":"No bandit error found.""}' > bandit-report.json
+    - uses: actions/upload-artifact@v1
+      with:
+        name: bandit_report
+        path: bandit-report.json
+    - name: comment bandit report in PR
+      uses: machine-learning-apps/pr-comment@master
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        path: bandit-report.json
+    - name: Check safety & bandit
+      run: |
+        poetry check
+        poetry run safety check --full-report
+        poetry run bandit -ll --recursive sample_components tests
+    - uses: gitleaks/gitleaks-action@v2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
   notify:
     runs-on: ubuntu-latest
     needs: [test_suite, linting_checks, formatting_checks, security_checks]
@@ -135,9 +246,9 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        repository: ${{ github.event.pull_request.head.repo.full_name }}
+        ref: ${{ github.event.pull_request.head.ref }}
     - uses: actions/download-artifact@v3
-    - name: Display structure of downloaded files
-      run: ls -R
     - name: Publish Sonar Cloud Result
       uses: SonarSource/sonarcloud-github-action@master
       env:
